---
AWSTemplateFormatVersion: 2010-09-09
Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: contest1
Outputs:
  S3BucketName:
    Description: Name of the S3 bucket
    Value: MyS3Bucket
