AWSTemplateFormatVersion: 2010-09-09

Resources:
  AthenaServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: athena.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AthenaPolicy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - athena:StartQueryExecution
                  - athena:GetQueryExecution
                  - athena:GetQueryResults
                  - athena:StopQueryExecution
                Resource: "*"
              - Effect: Allow
                Action:
                  - s3:GetBucketLocation
                  - s3:GetObject
                  - s3:ListBucket
                  - s3:ListBucketMultipartUploads
                  - s3:ListMultipartUploadParts
                  - s3:AbortMultipartUpload
                  - s3:CreateBucket
                  - s3:DeleteBucket
                  - s3:DeleteBucketPolicy
                  - s3:DeleteObject
                  - s3:DeleteObjectVersion
                  - s3:GetAccelerateConfiguration
                  - s3:GetBucketAcl
                  - s3:GetBucketCORS
                  - s3:GetBucketLocation
                  - s3:GetBucketLogging
                  - s3:GetBucketNotification
                  - s3:GetBucketPolicy
                  - s3:GetBucketRequestPayment
                  - s3:GetBucketTagging
                  - s3:GetBucketVersioning
                  - s3:GetBucketWebsite
                  - s3:GetLifecycleConfiguration
                  - s3:GetObjectAcl
                  - s3:GetObjectVersion
                  - s3:GetObjectVersionAcl
                  - s3:GetReplicationConfiguration
                  - s3:ListAllMyBuckets
                  - s3:PutAccelerateConfiguration
                  - s3:PutBucketAcl
                  - s3:PutBucketCORS
                  - s3:PutBucketLogging
                  - s3:PutBucketNotification
                  - s3:PutBucketPolicy
                  - s3:PutBucketRequestPayment
                  - s3:PutBucketTagging
                  - s3:PutBucketVersioning
                  - s3:PutBucketWebsite
                  - s3:PutLifecycleConfiguration
                  - s3:PutObject
                  - s3:PutObjectAcl
                  - s3:PutObjectVersionAcl
                  - s3:ReplicateObject
                Resource: "*"

  AthenaWorkGroup:
    Type: AWS::Athena::WorkGroup
    Properties:
      Name: cba_workgroup_name
      Description: WorkGroup for Athena queries
      State: ENABLED
      WorkGroupConfiguration:
        EnforceWorkGroupConfiguration: true
        ResultConfiguration:
          OutputLocation: s3://my-shiva881/data/

  NamedQuery:
    Type: AWS::Athena::NamedQuery
    Properties:
      Database: cbsgule  # Replace with your Glue database name
      Name: my_named_query
      Description: Example named query
      QueryString: >
        SELECT *
        FROM my_table
        WHERE column = 'value'

Outputs:
  AthenaWorkGroupOutput:
    Description: Output location for Athena queries
    Value:
      Ref: AthenaWorkGroup
