AWSTemplateFormatVersion: '2010-09-09'

Resources:
  MyJobRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          -
            Effect: 'Allow'
            Principal:
              Service:
                - glue.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Policies:
        -
          PolicyName: !Sub 'my-job-policy-${AWS::Region}'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              -
                Effect: 'Allow'
                Action:
                  - 'glue:*'
                  - 'athena:*'
                  - 's3:*'
                  - 'cloudtrail:*'
                  - 'logs:*'
                  - 'iam:ListRolePolicies'
                  - 'iam:GetRole'
                  - 'iam:GetRolePolicy'
                Resource: '*'